### ISSUE TITLE
Alert Services

### ISSUE THREAD

**Issue by amarkantk14** [cornflourblue/angular2-registration-login-example#3]
Hi Alert services is not working , I tried to dig out but unable to fix it.. I am new in angular2 , so please look in it.

import { Component, OnInit } from '@angular/core';
import { AlertService } from './../services/index';

@Component({
    moduleId: module.id,
    selector: 'alert',
    templateUrl: 'alert.component.html',
    providers: [AlertService],
})

export class AlertComponent implements OnInit {
    private message: any;

    constructor(private _alertService: AlertService) {}
    ngOnInit() {
        this._alertService.getMessage().subscribe(message => { 
            alert(message);  // on error this is not executing
        	this.message = message; 
        });
    }
}

**Comment by zohaib-buyer** [comment]
Hi i am facing same issue.

**Comment by cornflourblue** [comment]
Works fine for me, here's a plunk http://plnkr.co/edit/cJPED2?p=preview

To test enter an invalid username and password

**Comment by Prasannavk94** [comment]
Not working for me
