### ISSUE TITLE
ng serve is not working

### ISSUE THREAD

**Issue by alpeshrpatel** [cornflourblue/angular2-registration-login-example#9]
Versions of @angular/compiler-cli and typescript could not be determined.
The most common reason for this is a broken npm install.

Please make sure your package.json contains both @angular/compiler-cli and typescript in
devDependencies, then delete node_modules and package-lock.json (if you have one) and
run npm install again.

**Comment by NicoDino** [comment]
Hey @alpeshrpatel. 

Check if you're running with the correct version of the compiler-cli in your dev-dependencies (package.json)


cheers

**Comment by cornflourblue** [comment]
this project doesn't use angular-cli, for the cli version check out https://github.com/cornflourblue/angular2-registration-login-example-cli
